services:
  computer-use:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: computer-use
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${VNC_PORT}:${VNC_PORT}
      - ${DESKTOP_VIEW_PORT}:${DESKTOP_VIEW_PORT}
      - ${STREAMLIT_SERVER_PORT}:${STREAMLIT_SERVER_PORT}
    environment:
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
    volumes:
      - ${HOME}/.anthropic:/home/computeruse/.anthropic